import math
import os

def generate_sphere(filename, radius=1.0, slices=32, stacks=16):
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    with open(filename, 'w') as f:
        f.write("# Sphere generated by Python\n")
        f.write(f"o Sphere\n")
        
        # Vertices, Normals, UVs
        for i in range(stacks + 1):
            v = i / stacks
            phi = v * math.pi
            
            for j in range(slices + 1):
                u = j / slices
                theta = u * 2 * math.pi
                
                # Position & Normal
                x = math.cos(theta) * math.sin(phi)
                y = math.cos(phi)
                z = math.sin(theta) * math.sin(phi)
                
                f.write(f"v {x * radius} {y * radius} {z * radius}\n")
                f.write(f"vn {x} {y} {z}\n")
                f.write(f"vt {u} {1.0 - v}\n")
                
        # Faces
        for i in range(stacks):
            for j in range(slices):
                p1 = i * (slices + 1) + j + 1
                p2 = p1 + 1
                p3 = p1 + (slices + 1)
                p4 = p3 + 1
                
                # Face format: v/vt/vn
                f.write(f"f {p1}/{p1}/{p1} {p2}/{p2}/{p2} {p4}/{p4}/{p4} {p3}/{p3}/{p3}\n")

if __name__ == "__main__":
    generate_sphere("c:/Users/a3877/OneDrive/桌面/就職活動/simulator/resource/model/sphere.obj", radius=1.0)
    print("Generated sphere.obj")
